<a href="https://colab.research.google.com/github/Serin-Yoon/AI-for-Edustudents/blob/main/week13_sklearn_diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [18]:
from sklearn.datasets import load_diabetes
diabetes = load_diabetes()
#사이킷런의 당뇨병 환자 데이터셋 이용

In [5]:
print(diabetes.data.shape, diabetes.target.shape) #데이터 크기 확인

(442, 10) (442,)


In [6]:
diabetes.data[:3] #0~2번째 샘플 값

array([[ 0.03807591,  0.05068012,  0.06169621,  0.02187235, -0.0442235 ,
        -0.03482076, -0.04340085, -0.00259226,  0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, -0.02632783, -0.00844872,
        -0.01916334,  0.07441156, -0.03949338, -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, -0.00567061, -0.04559945,
        -0.03419447, -0.03235593, -0.00259226,  0.00286377, -0.02593034]])

In [7]:
diabetes.target[:3] #0~2번째 타겟 값 (타겟 값 = 당뇨병 진행 정도)

array([151.,  75., 141.])

In [19]:
import numpy as np

pa = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
a = np.array(pa)

In [ ]:
print(a[1, 0]) #numpy
print(a[1][0]) #numpy
print(pa[1][0]) #list

In [14]:
print(a[1])
print(pa[1])

[4 5 6]
[4, 5, 6]


In [ ]:
print(a[:, 1]) #모든 행의 1번째 열
print(a[:][1]) #모든 행, 그중 1번째 행
print(a[:2]) #0~1번째 행
print(a[:, 0:2]) #모든 행의 0~1번째 열

In [ ]:
print(a[:, 0]) #인덱싱 -> 차원 없어짐 (1차원)
print(a[:, 0:1]) #슬라이싱 -> 차원 그대로

In [23]:
import matplotlib.pyplot as plt

In [ ]:
plt.scatter(diabetes.data[:, 2], diabetes.target) #x는 모든 사람의 2번째 특성
plt.xlabel('x')
plt.ylabel('y')
plt.show()

In [ ]:
plt.scatter(diabetes.data[:10, 8], diabetes.target[:10])
plt.xlabel('x')
plt.ylabel('y')
plt.show()